import { ProjectsSectionType } from '@/lib/types/sections';
import { getId } from '@/lib/utils/helper';

export const projectsSection: ProjectsSectionType = {
  title: 'my projects',
  projects: [
    {
      id: getId(),
      name: 'Plant Disease Detection',
      url: 'https://plant-disease-prediction-project.streamlit.app/',
      repo: 'https://github.com/vatsalsinghkv/easy-fix',
      img: '/images/projects/pdp.png',
      year: 2025,
      tags: ['Python', 'Tensorflow', 'Streamlit', 'CNN'],
    },
    {
      id: getId(),
      name: 'SpaceScape',
      url: 'https://github.com/ayushshah31/spacewars',
      repo: 'https://github.com/ayushshah31/spacewars',
      img: '/images/projects/gdg.png',
      year: 2024,
      tags: ['Flutter', 'Game Development', 'Flutter Flame'],
    },
    {
      id: getId(),
      name: 'MedOps',
      url: 'https://www.figma.com/design/otsNvYqotQDbIbYmSKrXC2/Medops?node-id=0-1&p=f&t=FQnF7fxhLULgP0c3-0',
      repo: 'https://github.com/ayushshah31/medops',
      img: '/images/projects/medops.png',
      year: 2024,
      tags: ['Flutter','Dart', 'Firebase', 'Real-time', 'Data-stream'],
    },
    {
      id: getId(),
      name: 'Defi Lego',
      url: 'https://github.com/ayushshah31/COC_Spaghetti-Coders-1337-App',
      repo: 'https://github.com/ayushshah31/COC_Spaghetti-Coders-1337-App',
      img: '/images/projects/defi-lego.png',
      year: 2023,
      tags: ['Flutter', 'Web3', 'Nextjs', 'Dart', 'Nodejs', 'Solidity', 'Hackathon'],
    },
    {
      id: getId(),
      name: 'BitNBuild',
      url: 'https://github.com/ayushshah31/BitNBuild',
      repo: 'https://github.com/ayushshah31/BitNBuild',
      img: '/images/projects/bitnbuild.png',
      year: 2023,
      tags: ['Flutter', 'Firebase', 'Real-time', 'Healthcare', 'Hackathon'],
    },
    {
      id: getId(),
      name: 'Books Library Searching App',
      url: 'https://github.com/ayushshah31/books_library_new',
      repo: 'https://github.com/ayushshah31/books_library_new',
      img: '/images/projects/library.png',
      year: 2022,
      tags: ['Flutter', 'MongoDB', 'Library'],
    },
    {
      id: getId(),
      name: 'Travel Biddy',
      url: 'https://github.com/ayushshah31/travel_buddy',
      repo: 'https://github.com/ayushshah31/travel_buddy',
      img: '/images/projects/travel_buddy.png',
      year: 2021,
      tags: ['React', 'Google Maps', 'Planner','Web Development'],
    },
    {
      id: getId(),
      name: 'Committee Membership System',
      url: 'https://github.com/ayushshah31/travel_buddy',
      repo: 'https://github.com/ayushshah31/travel_buddy',
      img: '/images/projects/java-dbms.png',
      year: 2020,
      tags: ['React', 'Sass'],
    },
    // {
    //   id: getId(),
    //   name: 'rock paper scissors',
    //   url: 'https://rock-paper-scissors-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/rock-paper-scissors',
    //   img: 'https://user-images.githubusercontent.com/68834718/162578706-b9e57735-6fbc-4c7b-8243-2a6ba447404e.jpg',
    //   year: 2022,
    //   tags: ['React', 'Sass'],
    // },
    // {
    //   id: getId(),
    //   name: 'todo app',
    //   url: 'https://todo-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/todo-app',
    //   img: 'https://user-images.githubusercontent.com/68834718/152794002-0e7bc583-084b-4c39-83bb-d82d5dd642b2.png',
    //   year: 2022,
    //   tags: ['React', 'Sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'weather app',
    //   url: 'https://weather-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/weather-app',
    //   img: 'https://user-images.githubusercontent.com/68834718/148419702-491fa08d-e520-4e2f-b219-374ec7118b2b.png',
    //   year: 2022,
    //   tags: ['Html', 'sass', 'JS', 'jQuery'],
    // },
    // {
    //   id: getId(),
    //   name: 'blogr landing page',
    //   url: 'https://blogr-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/blogr-landing-page',
    //   img: 'https://user-images.githubusercontent.com/68834718/210222542-6455303d-c93e-430b-a5c8-96a431044184.png',
    //   year: 2021,
    //   tags: ['html', 'sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'natours',
    //   url: 'https://natours-kv.netlify.app/',
    //   repo: 'https://github.com/vatsalsinghkv/natours',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223114-b4f64b44-2501-49c9-9fb7-b8e53fe654c6.png',
    //   year: 2021,
    //   tags: ['html', 'sass', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'nexter',
    //   url: 'https://vatsalsinghkv.github.io/nexter/',
    //   repo: 'https://github.com/vatsalsinghkv/nexter',
    //   img: 'https://user-images.githubusercontent.com/68834718/210224671-5501c5d9-a8d2-4044-a14c-38fb7e46a113.png',
    //   year: 2021,
    //   tags: ['html', 'sass'],
    // },
    // {
    //   id: getId(),
    //   name: 'IP address tracker',
    //   url: 'https://vatsalsinghkv.github.io/ip-address-tracker/',
    //   repo: 'https://github.com/vatsalsinghkv/ip-address-tracker',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223386-03bcaa20-e649-4b3d-8709-59e42c6d685a.png',
    //   year: 2021,
    //   tags: ['html', 'bootstrap', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'calculator app',
    //   url: 'https://vatsalsinghkv.github.io/calculator-app/',
    //   repo: 'https://github.com/vatsalsinghkv/calculator-app/',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223825-3b68d696-39c6-490c-9433-f315b7efccbd.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'pig game',
    //   url: 'https://vatsalsinghkv.github.io/pig-game/',
    //   repo: 'https://github.com/vatsalsinghkv/pig-game',
    //   img: 'https://user-images.githubusercontent.com/68834718/210223527-de7fde7a-244e-4db5-8e33-d561afad6084.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
    // {
    //   id: getId(),
    //   name: 'bankist marketing',
    //   url: 'https://vatsalsinghkv.github.io/bankist-marketing/',
    //   repo: 'https://github.com/vatsalsinghkv/bankist-marketing',
    //   img: 'https://user-images.githubusercontent.com/68834718/210225545-989f79c3-cf05-4c53-b48e-b21f373b3734.png',
    //   year: 2021,
    //   tags: ['html', 'CSS', 'JS'],
    // },
  ],
};
